### PR TITLE
Swift 1.2 compatible

### PR DESCRIPTION
**Pull request by alexanderjarvis**

### CODE REVIEW

**Comment by jpsim** [comment]
Thanks @alexanderjarvis, but I already have a branch with these changes and more for the upcoming Swift 1.2 release: https://github.com/jpsim/PeerKit/compare/swift1p2.

**Comment by alexanderjarvis** [comment]
Thanks, but you also removed the compatibility with older versions of PeerKit at the same time.



On 23 March 2015 at 00:54:53, JP Simard (notifications@github.com) wrote:

Thanks @alexanderjarvis, but I already have a branch with these changes and more for the upcoming Swift 1.2 release: https://github.com/jpsim/PeerKit/compare/swift1p2.

**Comment by alexanderjarvis** [comment]
Yes but you also removed compatibility for the older PeerKit at the same time.

**Comment by jpsim** [comment]
> Thanks, but you also removed the compatibility with older versions of PeerKit at the same time.

Indeed. I'm still thinking about how long, if at all, we should keep the old approach.

**Comment by alexanderjarvis** [comment]
Agreed. I am happy to move forward. I would like to make the context to be able to be set by a client of PeerKit however (to identify users). Perhaps I'll submit a PR for this when I need it.

**Pull request closed without merging**
