### PR TITLE
Add podspec

### LINKED ISSUE #5: Distribute through CocoaPods
Would you be amenable to distributing PeerKit through CocoaPods? I'm sure this would make many people's lives a little easier. The [process](http://guides.cocoapods.org/making/specs-and-specs-repo.html) isn't too involved.

### PR DESCRIPTION
**Pull request by nickswalker**
Closes #5
I have run this through `pod spec lint` to verify the syntax. You will need to create a 1.0 tag for it to be fully functional.

### CODE REVIEW

**Comment by nickswalker** [comment]
You seem to be getting a healthy number of contributions, so I went ahead and added a [Travis-CI](https://travis-ci.org/) config to help you check at a glance that pull requests still build. If you think it's a good idea, you'll need to create an account with Travis (free), and link it to the repo (easy).

**Comment by nickswalker** [comment]
I got around to testing this today by adding this line to my podfile: `pod 'PeerKit', :git => "https://github.com/nickswalker/PeerKit.git"`. Works great.

**Comment by jpsim** [comment]
Hi @nickswalker, thanks for the PR!

Could you please update the podspec to point to v1.1.0 (tagged) and remove the `.travis.yml` file until Travis adds support for Xcode 6.3?

**Comment by nickswalker** [comment]
Done.

**Comment by jpsim** [comment]
The schemes and readme update no longer apply either, and the podspec is missing a newline at the end of the file. Otherwise, the PR looks good!

**Comment by jpsim** [comment]
Fantastic! Very sorry it took me so long to review.

**Pull request merged**
